gas:
  county:
    "Travis County": "Texas Gas Service"
    "Williamson County": "Texas Gas Service"
    "Hays County": "Texas Gas Service"
  zip:
    "78701": "Texas Gas Service"
    "78702": "Texas Gas Service"
    "78703": "Texas Gas Service"
    "78704": "Texas Gas Service"
    "78705": "Texas Gas Service"
    "78712": "Texas Gas Service"
    "78713": "Texas Gas Service"
    "78717": "Texas Gas Service"
    "78719": "Texas Gas Service"
    "78721": "Texas Gas Service"
    "78722": "Texas Gas Service"
    "78723": "Texas Gas Service"
    "78724": "Texas Gas Service"
    "78725": "Texas Gas Service"
    "78726": "Texas Gas Service"
    "78727": "Texas Gas Service"
    "78728": "Texas Gas Service"
    "78729": "Texas Gas Service"
    "78730": "Texas Gas Service"
    "78731": "Texas Gas Service"
    "78732": "Texas Gas Service"
    "78733": "Texas Gas Service"
    "78734": "Texas Gas Service"
    "78735": "Texas Gas Service"
    "78736": "Texas Gas Service"
    "78737": "Texas Gas Service"
    "78738": "Texas Gas Service"
    "78739": "Texas Gas Service"
    "78741": "Texas Gas Service"
    "78742": "Texas Gas Service"
    "78744": "Texas Gas Service"
    "78745": "Texas Gas Service"
    "78746": "Texas Gas Service"
    "78747": "Texas Gas Service"
    "78748": "Texas Gas Service"
    "78749": "Texas Gas Service"
    "78750": "Texas Gas Service"
    "78751": "Texas Gas Service"
    "78752": "Texas Gas Service"
    "78753": "Texas Gas Service"
    "78754": "Texas Gas Service"
    "78756": "Texas Gas Service"
    "78757": "Texas Gas Service"
    "78758": "Texas Gas Service"
    "78759": "Texas Gas Service"